# Copyright (c) 2026 Astrolune contributors
# SPDX-License-Identifier: MIT

[package]
name = "daemon"
description = "AstroLune node daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
config = { path = "../../crates/config" }
node = { path = "../../crates/node" }
types = { path = "../../crates/types" }

[lints]
workspace = true
