// Copyright (c) 2026 Astrolune contributors
// SPDX-License-Identifier: MIT

//! Wallet-mediated authorization for `AstroLune` applications.
//!
//! The protocol proves control of a wallet for a specific origin, audience,
//! nonce, scope set, chain, and short validity window. It never exposes the
//! wallet secret key to an application.

#![forbid(unsafe_code)]
#![allow(clippy::missing_errors_doc)]

use types::Address;

/// One application capability requested from a wallet.
#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum Scope {
    /// Read the public wallet address.
    Address,
    /// Ask the wallet to sign an application message.
    SignMessage,
    /// Ask the wallet to review and sign a transaction.
    SubmitTransaction,
}

/// Challenge generated by an application backend.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AuthorizationChallenge {
    /// Network replay-protection identifier.
    pub chain_id: u32,
    /// Normalized application origin.
    pub origin: String,
    /// Backend audience identifier.
    pub audience: String,
    /// Single-use unpredictable challenge.
    pub nonce: [u8; 32],
    /// Requested capabilities in canonical sorted order.
    pub scopes: Vec<Scope>,
    /// Earliest accepted protocol time.
    pub issued_at: u64,
    /// Last accepted protocol time.
    pub expires_at: u64,
}

/// Wallet response proving address control and user consent.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AuthorizationProof {
    /// Address shown to and approved by the user.
    pub address: Address,
    /// Canonical challenge bytes signed under the `ID` domain.
    pub challenge: AuthorizationChallenge,
    /// Wallet signature.
    pub signature: [u8; 64],
}

/// Verifies proof binding, expiry, signature, and nonce consumption.
pub trait AuthorizationVerifier {
    /// Consumes a valid nonce exactly once and returns the granted scopes.
    fn verify(&mut self, proof: &AuthorizationProof) -> Result<Vec<Scope>, IdError>;
}

/// Authorization failures safe to expose as protocol status codes.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum IdError {
    /// Challenge fields are malformed or non-canonical.
    InvalidChallenge,
    /// Challenge is outside its short validity window.
    Expired,
    /// Challenge nonce has already been consumed.
    Replay,
    /// Wallet signature is invalid.
    InvalidSignature,
}
