# Copyright (c) 2026 Astrolune contributors
# SPDX-License-Identifier: MIT

[package]
name = "cli"
description = "AstroLune operator and developer command-line interface"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
codec = { path = "../../crates/codec" }
config = { path = "../../crates/config" }
genesis = { path = "../../crates/genesis" }
keystore = { path = "../../crates/keystore" }
types = { path = "../../crates/types" }

[lints]
workspace = true
