# Copyright (c) 2026 Astrolune contributors
# SPDX-License-Identifier: MIT

[package]
name = "crypto"
description = "Cryptographic provider implementations for AstroLune"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
blake2 = "=0.11.0"
ed25519-dalek = "=3.0.0"
zeroize = "1.8"
types = { path = "../types" }

[lints]
workspace = true
